(define (min-removal nums k)
  (let* ([xs (list->vector (sort nums <))] [n (vector-length xs)])
    (let loop ([i 0] [mx 0])
      (if (< i n)
        (let ([j (search xs (* (vector-ref xs i) k))])
          (loop (+ i 1) (max mx (+ 1 (- j i))))
        )
        (- n mx)
      )
    )
  )
)

(define (search xs v)
  (let loop ([ok -1] [ng (vector-length xs)])
    (if (> (abs (- ok ng)) 1)
      (let ([mi (quotient (+ ok ng) 2)])
        (if (<= (vector-ref xs mi) v)
          (loop mi ng)
          (loop ok mi)
        )
      )
      ok
    )
  )
)
