(define (construct-transformed-array nums)
  (let ([n (length nums)])
    (let loop ([i 0])
      (if (< i n)
        (cons (list-ref nums (modulo (+ i (list-ref nums i)) n)) 
              (loop (+ i 1)))
        '()
      )
    )
  )
)
