(define (count-binary-substrings s)
  (let ([n (string-length s)])
    (let loop ([i 0] [x 0] [y 0] [total 0])
      (if (< i n)
        (if (or (= i 0) (equal? (string-ref s (- i 1)) (string-ref s i)))
          (loop (+ i 1) (+ x 1) y total)
          (loop (+ i 1) 1 x (+ total (min x y)))
        )
        (+ total (min x y))
      )
    )
  )
)
