(define (min-operations s)
  (let loop ((i 0) (v1 0) (v2 0))
    (if (< i (string-length s))
      (let ((d1 (if (= (modulo i 2) 0) #\0 #\1))
            (d2 (if (= (modulo i 2) 0) #\1 #\0)))
        (loop (+ i 1)
              (if (equal? (string-ref s i) d1) (+ v1 1) v1)
              (if (equal? (string-ref s i) d2) (+ v2 1) v2)))
      (min v1 v2))))
