(define (buy-choco prices money)
  (let loop ((vals prices) (v1 1000) (v2 1000))
    (if (null? vals)
      (if (<= (+ v1 v2) money)
        (- money (+ v1 v2))
        money)
      (cond ((<= (car vals) v1) (loop (cdr vals) (car vals) v1))
            ((<= (car vals) v2) (loop (cdr vals) v1 (car vals)))
            (else (loop (cdr vals) v1 v2))))))
