(define (intersect nums1 nums2)
    (if (null? nums1)
        '()
        (if (member (car nums1) nums2)
            (cons (car nums1) (intersect (cdr nums1) (remove (car nums1) nums2)))
            (intersect (cdr nums1) nums2)
        )
    )
)
