(define (max-score s)
  (define n (string-length s))
  (let loop ((i 1) 
             (l0 (if (is-zero s 0) 1 0))
             (r1 (if (is-zero s 0) (count-char s #\1) (- (count-char s #\1) 1))) 
             (ret -1))
    (if (= i n)
      ret
      (if (is-zero s i)
        (loop (+ i 1) (+ l0 1) r1 (max ret (+ l0 r1)))
        (loop (+ i 1) l0 (- r1 1) (max ret (+ l0 r1)))
      )
    )
  )
)

(define (count-char s c)
  (let loop ((i 0) (n 0))
    (if (< i (string-length s))
      (if (char=? (string-ref s i) c)
        (loop (+ i 1) (+ n 1))
        (loop (+ i 1) n)
      )
      n
    )
  )
)

(define (is-zero s i)
  (char=? (string-ref s i) #\0) 
)
