[package]
name = "shortest-subarray-to-be-removed-to-make-array-sorted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
